name: flutter_demo_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  google_maps_flutter: ^2.12.2
  intl: ^0.20.2
  confetti: ^0.8.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3 # ⬅️ Add this line

flutter_icons: # ⬅️ Icon configuration starts here
  android: true
  ios: true
  image_path: "assets/icon/icons.png" # ⬅️ Update this to your icon path
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icons.png # ⬅️ Ensure the icon is listed in assets
    - assets/dark_map_style.json
